### ISSUE TITLE
A TypeError can be thrown when comparing Yarn version with the template

### ISSUE THREAD

**Issue by mcmire** [MetaMask/template-sync#25]
When running this tool against a project with a `.yarnrc` file, the `.yarnrc` file is removed, then the Yarn version is checked, then this error is produced:

```
TypeError: version is longer than 256 characters
    at new SemVer (/Users/[redacted]/.yarn/berry/cache/semver-npm-7.6.0-f4630729f6-8.zip/node_modules/semver/classes/semver.js:23:13)
    at compare (/Users/[redacted]/.yarn/berry/cache/semver-npm-7.6.0-f4630729f6-8.zip/node_modules/semver/functions/compare.js:3:32)
    at Object.gt (/Users/[redacted]/.yarn/berry/cache/semver-npm-7.6.0-f4630729f6-8.zip/node_modules/semver/functions/gt.js:2:29)
    at checkYarnVersion (/Users/[redacted]/.yarn/berry/cache/@metamask-template-sync-npm-1.1.0-f571f9555f-8.zip/node_modules/@metamask/template-sync/dist/processing/yarnrc.js:51:36)
    at updateYarnRc (/Users/[redacted]/.yarn/berry/cache/@metamask-template-sync-npm-1.1.0-f571f9555f-8.zip/node_modules/@metamask/template-sync/dist/processing/yarnrc.js:82:11)
    at async task (/Users/[redacted]/.yarn/berry/cache/@metamask-template-sync-npm-1.1.0-f571f9555f-8.zip/node_modules/@metamask/template-sync/dist/cli.js:48:17)
    at async main (/Users/[redacted]/.yarn/berry/cache/@metamask-template-sync-npm-1.1.0-f571f9555f-8.zip/node_modules/@metamask/template-sync/dist/cli.js:114:9)
```

It seems that this is happening because the project doesn't use Node 18, and so `yarn --version` prints this instead:

```
Usage Error: This tool requires a Node version compatible with >=18.12.0 (got 16.20.2). Upgrade Node, or set `YARN_IGNORE_NODE=1` in your environment.

━━━ Yarn Package Manager - 4.1.1 ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  $ yarn <command>

You can also print more details about any of these commands by calling them with
the `-h,--help` flag right after the command name.
```

**Comment by mcmire** [comment]
On further investigation, this error seems to be happening because Node 18 is being set inside of the module template, and not the project. Therefore, I think this error seems specific to my setup. I don't think most people would run into this.
